defaults: &defaults
  allow_dynamic_fields: true
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true

production:
  <<: *defaults
  uri: <%= ENV['MONGOHQ_URL'] %>

development:
  <<: *defaults
  host: localhost
  database: billwaldo

test:
  <<: *defaults
  host: localhost
  database: testbillwaldo
